### ISSUE TITLE
程序报错：缺少click模块

### ISSUE THREAD

**Issue by shaobinqiu** [unkcpz/ababe#1]
When I run `runaba`, the package has error:

```python
Traceback (most recent call last):
  File "/home/qiusb/miniconda3/envs/ababe-py3/bin/runaba", line 11, in <module>
    load_entry_point('ababe', 'console_scripts', 'runaba')()
  File "/home/qiusb/miniconda3/envs/ababe-py3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/qiusb/miniconda3/envs/ababe-py3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2662, in load_entry_point
    return ep.load()
  File "/home/qiusb/miniconda3/envs/ababe-py3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2316, in load
    return self.resolve()
  File "/home/qiusb/miniconda3/envs/ababe-py3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2322, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/qiusb/Projects/ababe/ababe/cmdline/runabalib.py", line 5, in <module>
    import click
ModuleNotFoundError: No module named 'click'
```

**Comment by unkcpz** [comment]
Thanks.
add click in setup.py.
